#cloud-config-mkdocs-system

groups:
  - ubuntu: [root,sys]
  - ansible-group

users:
  - default
  - name: hulk
    gecos: Dr. Banner
    shell: /bin/bash
    primary_group: ansible-group
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
    # Enter your key here:
      - ssh-rsa AAAA....

runcmd:
  - touch /home/hulk/hello.txt
  - echo "HULK SMASH WHEN DONE!!" >> /home/hulk/hello.txt
  - mkdir asteroids
  - sudo apt update

## Create ssh key and copy to Azure VM (may have to do that via the bash script), then copy data